### ISSUE TITLE
Are you planning to adapt fluxgym for modal? 

### ISSUE THREAD

**Issue by Dragoy** [punitda/modal-flux-lora-trainer#1]
You mentioned in your video that you also plan to release a fluxgym version, were you able to do that?

**Comment by punitda** [comment]
@Dragoy Sorry for the delayed response. I haven’t had the time to implement the Flux Gym module. I’ll reopen this issue and add support for it within the next couple of weeks.

**Comment by Dragoy** [comment]
> @Dragoy Sorry for the delayed response. I haven’t had the time to implement the Flux Gym module. I’ll reopen this issue and add support for it within the next couple of weeks.

That's okay, thanks for responding. I closed the issue because I wrote my own version of the application that runs fluxgym training on modal.

**Comment by punitda** [comment]
That's great! If you open source it let me know, I'd be happy to link it in the repo.

**Comment by Dragoy** [comment]
> That's great! If you open source it let me know, I'd be happy to link it in the repo.

Great idea, only I will ask your help to check my code, there is some asynchrony problem there, maybe you can solve it.

upd: sent the invite

**Comment by punitda** [comment]
Sounds good! I'll take a look

**Comment by Dragoy** [comment]
@punitda 
have you ever encountered any of these errors? 
Because of it the training doesn't work longer than one hour :(
I think it's a problem with modal itself. 

```
Task exception was never retrieved
future: <Task finished name='Task-3768' coro=<_proxy_http_request.<locals>.send_response() done, defined at /pkg/modal/_asgi.py:231> exception=TimeoutError()>
Traceback (most recent call last):
  File "/pkg/modal/_asgi.py", line 238, in send_response
    async for data in proxy_response.content.iter_any():
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 35, in __anext__
    rv = await self.read_func()
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 397, in readany
    await self._wait("readany")
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 303, in _wait
    with self._timer:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 720, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError


    GET /queue/data -> 200 OK  (duration: 3601.2 s, execution: 3600.7 s)


Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7eefd4a89590>
Exception ignored in: <function ClientResponse.__del__ at 0x7eefd51e0860>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 811, in __del__    
    self._connection.release()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 178, in release        
    self._connector._release(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 663, in _release       
    protocol.close()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_proto.py", line 63, in close        
    transport.close()
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 860, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function ClientResponse.__del__ at 0x7eefd51e0860>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 811, in __del__    
    self._connection.release()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 178, in release        
    self._connector._release(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 663, in _release       
    protocol.close()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_proto.py", line 63, in close        
    transport.close()
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 860, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by punitda** [comment]
I looked at your implementation. Based on it, it shouldn't [timeout](https://modal.com/docs/guide/timeouts#timeouts) before 2 hrs

@Dragoy  Are you deploying the app and then accessing it via app url? or running it locally via modal serve?

**Comment by punitda** [comment]
Ignore my above comment. I don't think so there is any difference between deployed and ephemeral apps when it comes to functions timeout

**Comment by Dragoy** [comment]
> Ignore my above comment. I don't think so there is any difference between deployed and ephemeral apps when it comes to functions timeout

Yes, I run it using serve. 

I also wrote to the modal developers in their slack. I have provided them with all the necessary information to reproduce this error, we will wait for their response.

**Comment by Woukim** [comment]
> > Ignore my above comment. I don't think so there is any difference between deployed and ephemeral apps when it comes to functions timeout
> 
> Yes, I run it using serve.
> 
> I also wrote to the modal developers in their slack. I have provided them with all the necessary information to reproduce this error, we will wait for their response.

Is there any news??? i'm experiencing this problem right now, i set the training to 2000 steps and every time it crashes.

**Comment by Dragoy** [comment]
> Yes, I run it using serve.
> 
> I also wrote to the modal developers in their slack. I have provided them with all the necessary information to reproduce this error, we will wait for their response.

That's the whole problem:
https://github.com/modal-labs/modal-client/blob/b61aed4330feada82bee7e2b27190b2c07925fe1/modal/_asgi.py#L323

**Comment by MubTaXim** [comment]
so are there any fixes yet?

**Comment by Dragoy** [comment]
> so are there any fixes yet?

What problems have you encountered?

**Comment by MubTaXim** [comment]
> > so are there any fixes yet?
> 
> What problems have you encountered?

Gettings this error and the gpu stops training. Maybe it loses connection to the gradio that's why?



Task exception was never retrieved
future: <Task finished name='Task-6908' coro=<_proxy_http_request.<locals>.send_response() done, defined at /pkg/modal/_runtime/asgi.py:374> exception=ClientPayloadError("Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_proto.py", line 92, in connection_lost
    uncompleted = self._parser.feed_eof()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 513, in aiohttp._http_parser.HttpParser.feed_eof
aiohttp.http_exceptions.TransferEncodingError: 400, message:
  Not enough data for satisfy transfer length header.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/pkg/modal/_runtime/asgi.py", line 381, in send_response
    async for data in proxy_response.content.iter_any():
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 50, in __anext__
    rv = await self.read_func()
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 408, in readany
    await self._wait("readany")
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 315, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>
